name: CI Pipeline with SonarQube SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17  # Updated to Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Recommended Java distribution

      - name: Cache SonarQube Scanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/*.java') }}
          restore-keys: |
            sonar-${{ runner.os }}-

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=donpower_repos \
            -Dsonar.sources=sonar-example-test/sonar-scanning-examples-master/sonar-scanner-gradle/gradle-basic/src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
